/****************************************************************************
**
** Namespace SecCtrlLib generated by dumpcpp v5.12.3 using
** dumpcpp.exe D:\Qt\SKF_FileList\npSecCtrl.dll
** from the type library D:\Qt\SKF_FileList\npSecCtrl.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_SECCTRLLIB_H
#define QAX_DUMPCPP_SECCTRLLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef SECCTRLLIB_EXPORT
#define SECCTRLLIB_EXPORT
#endif
#include <ActiveQt/QAxObject.h>
#include <ActiveQt/QAxWidget.h>
//#include <qaxobject.h>
//#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace SecCtrlLib {


class SECCTRLLIB_EXPORT ICACtrlCom : public QAxObject
{
public:
    ICACtrlCom(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method GetCN
    */
    inline int GetCN(QString& bstrInfo);

    /*
    Method GetCerBase64
    */
    inline int GetCerBase64(QString& CerBase64);

    /*
    Method GetDriverVersion
    */
    inline int GetDriverVersion(QString& bstrVersion);

    /*
    Method GetErrorInfo
    */
    inline void GetErrorInfo(int& errCode, QString& bstrErrorMsg);

    /*
    Method GetFws
    */
    inline int GetFws(QString& bstrFws);

    /*
    Method GetSbtgs
    */
    inline int GetSbtgs(QString& bstrPcVid);

    /*
    Method GetUserMc
    */
    inline int GetUserMc(QString& CertUserMc);

    /*
    Method GetYxqz
    */
    inline int GetYxqz(QString& Yxqz);

    /*
    Method KS_AZTSignData
    */
    inline QString KS_AZTSignData(const QString& bstrInData);

    /*
    Method KS_ChangeSoftPIN
    */
    inline int KS_ChangeSoftPIN(const QString& bstrOldPin, const QString& bstrNewPin);

    /*
    Method KS_CheckPIN
    */
    inline int KS_CheckPIN(const QString& bstrPin);

    /*
    Method KS_DeleteEmptyApp
    */
    inline int KS_DeleteEmptyApp();

    /*
    Method KS_DeleteFromKey
    */
    inline int KS_DeleteFromKey();

    /*
    Method KS_FormatDev
    */
    inline int KS_FormatDev();

    /*
    Method KS_GenKeyPair
    */
    inline QString KS_GenKeyPair();

    /*
    Method KS_GenP10Indata
    */
    inline QString KS_GenP10Indata(const QString& bstrDn, const QString& bstrPub, int lHashAlg);

    /*
    Method KS_GenRandom
    */
    inline QString KS_GenRandom(int lLen);

    /*
    Method KS_GetALLDevice
    */
    inline QString KS_GetALLDevice();

    /*
    Method KS_GetASN1ByParseJSON
    */
    inline QString KS_GetASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method KS_GetAllDeviceSerialNumber
    */
    inline QString KS_GetAllDeviceSerialNumber();

    /*
    Method KS_GetCert
    */
    inline QString KS_GetCert(int lType);

    /*
    Method KS_GetCertFromNet
    */
    inline QString KS_GetCertFromNet(const QString& lID);

    /*
    Method KS_GetCertInfo
    */
    inline QString KS_GetCertInfo(const QString& bstrCert, int lType);

    /*
    Method KS_GetCertInfoByOid
    */
    inline QString KS_GetCertInfoByOid(const QString& bstrCert, const QString& bstrOid);

    /*
    Method KS_GetDeviceCSP
    */
    inline QString KS_GetDeviceCSP();

    /*
    Method KS_GetDeviceSerialNumber
    */
    inline QString KS_GetDeviceSerialNumber();

    /*
    Method KS_GetDeviceStatus
    */
    inline int KS_GetDeviceStatus();

    /*
    Method KS_GetDeviceVid
    */
    inline QString KS_GetDeviceVid();

    /*
    Method KS_GetESignASN1ByParseJSON
    */
    inline QString KS_GetESignASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method KS_GetImage
    */
    inline QString KS_GetImage(const QString& bStrShebao, const QString& bStrO);

    /*
    Method KS_GetImageByParseConfig
    */
    inline QString KS_GetImageByParseConfig();

    /*
    Method KS_GetImageFromKey
    */
    inline QString KS_GetImageFromKey();

    /*
    Method KS_GetInfoFromSeal
    */
    inline QString KS_GetInfoFromSeal(const QString& bstrSealData, int lType);

    /*
    Method KS_GetLastErrorCode
    */
    inline int KS_GetLastErrorCode();

    /*
    Method KS_GetLastErrorMsg
    */
    inline QString KS_GetLastErrorMsg();

    /*
    Method KS_GetP10Info
    */
    inline QString KS_GetP10Info(const QString& bstrP10, int lAlg, int lType);

    /*
    Method KS_GetParam
    */
    inline QString KS_GetParam(const QString& bstrParamName);

    /*
    Method KS_GetSeal
    */
    inline QString KS_GetSeal(const QString& bstrSealId);

    /*
    Method KS_GetSealImage
    */
    inline QString KS_GetSealImage(int lType, const QString& bStrCn);

    /*
    Method KS_GetSealList
    */
    inline QString KS_GetSealList();

    /*
    Method KS_GetSignValueFromNet
    */
    inline QString KS_GetSignValueFromNet(const QString& lID, int time);

    /*
    Method KS_GetVersion
    */
    inline QString KS_GetVersion();

    /*
    Method KS_GetXJLVersion
    */
    inline QString KS_GetXJLVersion();

    /*
    Method KS_GetZDYFYUsedKeyFactory
    */
    inline QString KS_GetZDYFYUsedKeyFactory();

    /*
    Method KS_HashData
    */
    inline QString KS_HashData(const QString& bstrInData, int lAlg);

    /*
    Method KS_HashFile
    */
    inline QString KS_HashFile(const QString& bstrFile, int lAlg);

    /*
    Method KS_ImportP12Cert
    */
    inline int KS_ImportP12Cert(int lCertType, const QString& bstrBase64P12Cert, const QString& bstrPin);

    /*
    Method KS_IsChangeKey
    */
    inline int KS_IsChangeKey();

    /*
    Method KS_MakeEnvelope
    */
    inline QString KS_MakeEnvelope(const QString& bstrOriData, const QString& bstrBase64Cert);

    /*
    Method KS_MakeICP10
    */
    inline QString KS_MakeICP10(const QString& bstrSignData, const QString& bstrAsn1Indata, int lHashAlg);

    /*
    Method KS_MakeP10
    */
    inline QString KS_MakeP10(const QString& bstrDn, int lHashAlg);

    /*
    Method KS_MakeP10AccPub
    */
    inline QString KS_MakeP10AccPub(const QString& bstrDn, const QString& bstrPub, int lHashAlg);

    /*
    Method KS_OpenEnvelope
    */
    inline QString KS_OpenEnvelope(const QString& bstrEnvelope);

    /*
    Method KS_OpenIE
    */
    inline int KS_OpenIE(const QString& ieUrl);

    /*
    Method KS_ReadFromKey
    */
    inline QString KS_ReadFromKey(int iType);

    /*
    Method KS_ReceiveCert
    */
    inline QString KS_ReceiveCert(const QString& bstrID, const QString& bstrServerAdd);

    /*
    Method KS_RemoveCert
    */
    inline int KS_RemoveCert();

    /*
    Method KS_SM3HashWithPreProcess
    */
    inline QString KS_SM3HashWithPreProcess(const QString& pcPub, const QString& Indata, int lHashAlg);

    /*
    Method KS_SaveCert
    */
    inline int KS_SaveCert(const QString& bstrSignCert, const QString& bstrEncCert, const QString& bstrEncKey);

    /*
    Method KS_SaveCertChain
    */
    inline int KS_SaveCertChain(const QString& bstrP7CertChain);

    /*
    Method KS_SaveImage
    */
    inline int KS_SaveImage(const QString& bStrCn, const QString& bStrO, const QString& filePath);

    /*
    Method KS_SendP10
    */
    inline int KS_SendP10(const QString& bstrID, const QString& bstrP10, const QString& bstrDn, const QString& bstrIP, int port);

    /*
    Method KS_SetConfigToKey
    */
    inline int KS_SetConfigToKey(const QString& bstrFile);

    /*
    Method KS_SetImageToKey
    */
    inline int KS_SetImageToKey(const QString& bstrFile);

    /*
    Method KS_SetParam
    */
    inline int KS_SetParam(const QString& bstrParamName, const QString& bstrParamData);

    /*
    Method KS_SetProv
    */
    inline int KS_SetProv(const QString& bstrProv, int lAlg, const QString& bstrPath);

    /*
    Method KS_SetServiceAdd
    */
    inline int KS_SetServiceAdd(int bstrID, const QString& bstrAddr);

    /*
    Method KS_SetSoftKey
    */
    inline int KS_SetSoftKey(const QString& bstrAppName, const QString& bstrContName, const QString& bstrPin, const QString& bstrAppID, const QString& bstrDevName);

    /*
    Method KS_SignData
    */
    inline QString KS_SignData(const QString& bstrInData, int lHashAlg);

    /*
    Method KS_SymmDecrypt
    */
    inline QString KS_SymmDecrypt(const QString& bstrEncData, const QString& bstrKey, int lSymmAlg);

    /*
    Method KS_SymmEncrypt
    */
    inline QString KS_SymmEncrypt(const QString& bstrOriData, const QString& bstrKey, int lSymmAlg);

    /*
    Method KS_Test
    */
    inline int KS_Test();

    /*
    Method KS_UnblockPIN
    */
    inline int KS_UnblockPIN(const QString& bstrAdminPIN, const QString& bstrUserPIN);

    /*
    Method KS_UniversalHashData
    */
    inline QString KS_UniversalHashData(const QString& bstrInData, const QString& bstrCert, int lAlg);

    /*
    Method KS_UniversalHashFile
    */
    inline QString KS_UniversalHashFile(const QString& bstrData, const QString& bstrFile, int lAlg, const QString& bstrCert);

    /*
    Method KS_UniversalSignData
    */
    inline QString KS_UniversalSignData(const QString& bstrData, const QString& bstrInData, int lHashAlg);

    /*
    Method KS_UniversalVerifySignData
    */
    inline void KS_UniversalVerifySignData(const QString& bstrData, const QString& bstrInData, const QString& bstrSignData);

    /*
    Method KS_VerifyCertVaild
    */
    inline int KS_VerifyCertVaild(const QString& bstrCert);

    /*
    Method KS_VerifyESignSeal
    */
    inline int KS_VerifyESignSeal(const QString& bstrESignSealData);

    /*
    Method KS_VerifyP7SignData
    */
    inline int KS_VerifyP7SignData(const QString& bstrP7SignData);

    /*
    Method KS_VerifyPIN
    */
    inline int KS_VerifyPIN();

    /*
    Method KS_VerifySeal
    */
    inline int KS_VerifySeal(const QString& bstrSealId);

    /*
    Method KS_VerifySignData
    */
    inline int KS_VerifySignData(const QString& bstrInData, const QString& bstrSignData, const QString& bstrCert, int lHashAlg);

    /*
    Method KS_VerifySoftPIN
    */
    inline int KS_VerifySoftPIN(const QString& bstrPin);

    /*
    Method KS_WriteToKey
    */
    inline int KS_WriteToKey(int iType, const QString& bstrFile);

    /*
    Method KS_ZWFWGetASN1ByParseJSON
    */
    inline QString KS_ZWFWGetASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method SetCert
    */
    inline int SetCert(const QString& strCertBase64);

    /*
    Method Sign
    */
    inline int Sign(const QString& bstrInData, QString& bstrSignData);

    /*
    Method TestFunction
    */
    inline int TestFunction(int i);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class SECCTRLLIB_EXPORT CACtrlCom : public QAxObject
{
public:
    CACtrlCom(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl(QStringLiteral("{17f8d3cf-857c-4d7c-9355-7a2398930b6a}"));
    }

    CACtrlCom(ICACtrlCom *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method GetCN
    */
    inline int GetCN(QString& bstrInfo);

    /*
    Method GetCerBase64
    */
    inline int GetCerBase64(QString& CerBase64);

    /*
    Method GetDriverVersion
    */
    inline int GetDriverVersion(QString& bstrVersion);

    /*
    Method GetErrorInfo
    */
    inline void GetErrorInfo(int& errCode, QString& bstrErrorMsg);

    /*
    Method GetFws
    */
    inline int GetFws(QString& bstrFws);

    /*
    Method GetSbtgs
    */
    inline int GetSbtgs(QString& bstrPcVid);

    /*
    Method GetUserMc
    */
    inline int GetUserMc(QString& CertUserMc);

    /*
    Method GetYxqz
    */
    inline int GetYxqz(QString& Yxqz);

    /*
    Method KS_AZTSignData
    */
    inline QString KS_AZTSignData(const QString& bstrInData);

    /*
    Method KS_ChangeSoftPIN
    */
    inline int KS_ChangeSoftPIN(const QString& bstrOldPin, const QString& bstrNewPin);

    /*
    Method KS_CheckPIN
    */
    inline int KS_CheckPIN(const QString& bstrPin);

    /*
    Method KS_DeleteEmptyApp
    */
    inline int KS_DeleteEmptyApp();

    /*
    Method KS_DeleteFromKey
    */
    inline int KS_DeleteFromKey();

    /*
    Method KS_FormatDev
    */
    inline int KS_FormatDev();

    /*
    Method KS_GenKeyPair
    */
    inline QString KS_GenKeyPair();

    /*
    Method KS_GenP10Indata
    */
    inline QString KS_GenP10Indata(const QString& bstrDn, const QString& bstrPub, int lHashAlg);

    /*
    Method KS_GenRandom
    */
    inline QString KS_GenRandom(int lLen);

    /*
    Method KS_GetALLDevice
    */
    inline QString KS_GetALLDevice();

    /*
    Method KS_GetASN1ByParseJSON
    */
    inline QString KS_GetASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method KS_GetAllDeviceSerialNumber
    */
    inline QString KS_GetAllDeviceSerialNumber();

    /*
    Method KS_GetCert
    */
    inline QString KS_GetCert(int lType);

    /*
    Method KS_GetCertFromNet
    */
    inline QString KS_GetCertFromNet(const QString& lID);

    /*
    Method KS_GetCertInfo
    */
    inline QString KS_GetCertInfo(const QString& bstrCert, int lType);

    /*
    Method KS_GetCertInfoByOid
    */
    inline QString KS_GetCertInfoByOid(const QString& bstrCert, const QString& bstrOid);

    /*
    Method KS_GetDeviceCSP
    */
    inline QString KS_GetDeviceCSP();

    /*
    Method KS_GetDeviceSerialNumber
    */
    inline QString KS_GetDeviceSerialNumber();

    /*
    Method KS_GetDeviceStatus
    */
    inline int KS_GetDeviceStatus();

    /*
    Method KS_GetDeviceVid
    */
    inline QString KS_GetDeviceVid();

    /*
    Method KS_GetESignASN1ByParseJSON
    */
    inline QString KS_GetESignASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method KS_GetImage
    */
    inline QString KS_GetImage(const QString& bStrShebao, const QString& bStrO);

    /*
    Method KS_GetImageByParseConfig
    */
    inline QString KS_GetImageByParseConfig();

    /*
    Method KS_GetImageFromKey
    */
    inline QString KS_GetImageFromKey();

    /*
    Method KS_GetInfoFromSeal
    */
    inline QString KS_GetInfoFromSeal(const QString& bstrSealData, int lType);

    /*
    Method KS_GetLastErrorCode
    */
    inline int KS_GetLastErrorCode();

    /*
    Method KS_GetLastErrorMsg
    */
    inline QString KS_GetLastErrorMsg();

    /*
    Method KS_GetP10Info
    */
    inline QString KS_GetP10Info(const QString& bstrP10, int lAlg, int lType);

    /*
    Method KS_GetParam
    */
    inline QString KS_GetParam(const QString& bstrParamName);

    /*
    Method KS_GetSeal
    */
    inline QString KS_GetSeal(const QString& bstrSealId);

    /*
    Method KS_GetSealImage
    */
    inline QString KS_GetSealImage(int lType, const QString& bStrCn);

    /*
    Method KS_GetSealList
    */
    inline QString KS_GetSealList();

    /*
    Method KS_GetSignValueFromNet
    */
    inline QString KS_GetSignValueFromNet(const QString& lID, int time);

    /*
    Method KS_GetVersion
    */
    inline QString KS_GetVersion();

    /*
    Method KS_GetXJLVersion
    */
    inline QString KS_GetXJLVersion();

    /*
    Method KS_GetZDYFYUsedKeyFactory
    */
    inline QString KS_GetZDYFYUsedKeyFactory();

    /*
    Method KS_HashData
    */
    inline QString KS_HashData(const QString& bstrInData, int lAlg);

    /*
    Method KS_HashFile
    */
    inline QString KS_HashFile(const QString& bstrFile, int lAlg);

    /*
    Method KS_ImportP12Cert
    */
    inline int KS_ImportP12Cert(int lCertType, const QString& bstrBase64P12Cert, const QString& bstrPin);

    /*
    Method KS_IsChangeKey
    */
    inline int KS_IsChangeKey();

    /*
    Method KS_MakeEnvelope
    */
    inline QString KS_MakeEnvelope(const QString& bstrOriData, const QString& bstrBase64Cert);

    /*
    Method KS_MakeICP10
    */
    inline QString KS_MakeICP10(const QString& bstrSignData, const QString& bstrAsn1Indata, int lHashAlg);

    /*
    Method KS_MakeP10
    */
    inline QString KS_MakeP10(const QString& bstrDn, int lHashAlg);

    /*
    Method KS_MakeP10AccPub
    */
    inline QString KS_MakeP10AccPub(const QString& bstrDn, const QString& bstrPub, int lHashAlg);

    /*
    Method KS_OpenEnvelope
    */
    inline QString KS_OpenEnvelope(const QString& bstrEnvelope);

    /*
    Method KS_OpenIE
    */
    inline int KS_OpenIE(const QString& ieUrl);

    /*
    Method KS_ReadFromKey
    */
    inline QString KS_ReadFromKey(int iType);

    /*
    Method KS_ReceiveCert
    */
    inline QString KS_ReceiveCert(const QString& bstrID, const QString& bstrServerAdd);

    /*
    Method KS_RemoveCert
    */
    inline int KS_RemoveCert();

    /*
    Method KS_SM3HashWithPreProcess
    */
    inline QString KS_SM3HashWithPreProcess(const QString& pcPub, const QString& Indata, int lHashAlg);

    /*
    Method KS_SaveCert
    */
    inline int KS_SaveCert(const QString& bstrSignCert, const QString& bstrEncCert, const QString& bstrEncKey);

    /*
    Method KS_SaveCertChain
    */
    inline int KS_SaveCertChain(const QString& bstrP7CertChain);

    /*
    Method KS_SaveImage
    */
    inline int KS_SaveImage(const QString& bStrCn, const QString& bStrO, const QString& filePath);

    /*
    Method KS_SendP10
    */
    inline int KS_SendP10(const QString& bstrID, const QString& bstrP10, const QString& bstrDn, const QString& bstrIP, int port);

    /*
    Method KS_SetConfigToKey
    */
    inline int KS_SetConfigToKey(const QString& bstrFile);

    /*
    Method KS_SetImageToKey
    */
    inline int KS_SetImageToKey(const QString& bstrFile);

    /*
    Method KS_SetParam
    */
    inline int KS_SetParam(const QString& bstrParamName, const QString& bstrParamData);

    /*
    Method KS_SetProv
    */
    inline int KS_SetProv(const QString& bstrProv, int lAlg, const QString& bstrPath);

    /*
    Method KS_SetServiceAdd
    */
    inline int KS_SetServiceAdd(int bstrID, const QString& bstrAddr);

    /*
    Method KS_SetSoftKey
    */
    inline int KS_SetSoftKey(const QString& bstrAppName, const QString& bstrContName, const QString& bstrPin, const QString& bstrAppID, const QString& bstrDevName);

    /*
    Method KS_SignData
    */
    inline QString KS_SignData(const QString& bstrInData, int lHashAlg);

    /*
    Method KS_SymmDecrypt
    */
    inline QString KS_SymmDecrypt(const QString& bstrEncData, const QString& bstrKey, int lSymmAlg);

    /*
    Method KS_SymmEncrypt
    */
    inline QString KS_SymmEncrypt(const QString& bstrOriData, const QString& bstrKey, int lSymmAlg);

    /*
    Method KS_Test
    */
    inline int KS_Test();

    /*
    Method KS_UnblockPIN
    */
    inline int KS_UnblockPIN(const QString& bstrAdminPIN, const QString& bstrUserPIN);

    /*
    Method KS_UniversalHashData
    */
    inline QString KS_UniversalHashData(const QString& bstrInData, const QString& bstrCert, int lAlg);

    /*
    Method KS_UniversalHashFile
    */
    inline QString KS_UniversalHashFile(const QString& bstrData, const QString& bstrFile, int lAlg, const QString& bstrCert);

    /*
    Method KS_UniversalSignData
    */
    inline QString KS_UniversalSignData(const QString& bstrData, const QString& bstrInData, int lHashAlg);

    /*
    Method KS_UniversalVerifySignData
    */
    inline void KS_UniversalVerifySignData(const QString& bstrData, const QString& bstrInData, const QString& bstrSignData);

    /*
    Method KS_VerifyCertVaild
    */
    inline int KS_VerifyCertVaild(const QString& bstrCert);

    /*
    Method KS_VerifyESignSeal
    */
    inline int KS_VerifyESignSeal(const QString& bstrESignSealData);

    /*
    Method KS_VerifyP7SignData
    */
    inline int KS_VerifyP7SignData(const QString& bstrP7SignData);

    /*
    Method KS_VerifyPIN
    */
    inline int KS_VerifyPIN();

    /*
    Method KS_VerifySeal
    */
    inline int KS_VerifySeal(const QString& bstrSealId);

    /*
    Method KS_VerifySignData
    */
    inline int KS_VerifySignData(const QString& bstrInData, const QString& bstrSignData, const QString& bstrCert, int lHashAlg);

    /*
    Method KS_VerifySoftPIN
    */
    inline int KS_VerifySoftPIN(const QString& bstrPin);

    /*
    Method KS_WriteToKey
    */
    inline int KS_WriteToKey(int iType, const QString& bstrFile);

    /*
    Method KS_ZWFWGetASN1ByParseJSON
    */
    inline QString KS_ZWFWGetASN1ByParseJSON(const QString& bstrJsonData, int lFlag);

    /*
    Method SetCert
    */
    inline int SetCert(const QString& strCertBase64);

    /*
    Method Sign
    */
    inline int Sign(const QString& bstrInData, QString& bstrSignData);

    /*
    Method TestFunction
    */
    inline int TestFunction(int i);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_SECCTRLLIB_NOINLINES
inline int CACtrlCom::GetCN(QString& bstrInfo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInfo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int CACtrlCom::GetCerBase64(QString& CerBase64)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&CerBase64};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int CACtrlCom::GetDriverVersion(QString& bstrVersion)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrVersion};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline void CACtrlCom::GetErrorInfo(int& errCode, QString& bstrErrorMsg)
{
    void *_a[] = {0, (void*)&errCode, (void*)&bstrErrorMsg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline int CACtrlCom::GetFws(QString& bstrFws)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFws};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int CACtrlCom::GetSbtgs(QString& bstrPcVid)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPcVid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int CACtrlCom::GetUserMc(QString& CertUserMc)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&CertUserMc};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int CACtrlCom::GetYxqz(QString& Yxqz)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Yxqz};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_AZTSignData(const QString& bstrInData)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int CACtrlCom::KS_ChangeSoftPIN(const QString& bstrOldPin, const QString& bstrNewPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOldPin, (void*)&bstrNewPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int CACtrlCom::KS_CheckPIN(const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int CACtrlCom::KS_DeleteEmptyApp()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int CACtrlCom::KS_DeleteFromKey()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int CACtrlCom::KS_FormatDev()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GenKeyPair()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GenP10Indata(const QString& bstrDn, const QString& bstrPub, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&bstrPub, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GenRandom(int lLen)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lLen};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetALLDevice()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetAllDeviceSerialNumber()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetCert(int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetCertFromNet(const QString& lID)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 29, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetCertInfo(const QString& bstrCert, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 30, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetCertInfoByOid(const QString& bstrCert, const QString& bstrOid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert, (void*)&bstrOid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetDeviceCSP()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetDeviceSerialNumber()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
    return qax_result;
}

inline int CACtrlCom::KS_GetDeviceStatus()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetDeviceVid()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetESignASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetImage(const QString& bStrShebao, const QString& bStrO)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bStrShebao, (void*)&bStrO};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetImageByParseConfig()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetImageFromKey()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetInfoFromSeal(const QString& bstrSealData, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealData, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline int CACtrlCom::KS_GetLastErrorCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetLastErrorMsg()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetP10Info(const QString& bstrP10, int lAlg, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP10, (void*)&lAlg, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetParam(const QString& bstrParamName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrParamName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetSeal(const QString& bstrSealId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetSealImage(int lType, const QString& bStrCn)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lType, (void*)&bStrCn};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetSealList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetSignValueFromNet(const QString& lID, int time)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lID, (void*)&time};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetVersion()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetXJLVersion()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_GetZDYFYUsedKeyFactory()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_HashData(const QString& bstrInData, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_HashFile(const QString& bstrFile, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline int CACtrlCom::KS_ImportP12Cert(int lCertType, const QString& bstrBase64P12Cert, const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lCertType, (void*)&bstrBase64P12Cert, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
    return qax_result;
}

inline int CACtrlCom::KS_IsChangeKey()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_MakeEnvelope(const QString& bstrOriData, const QString& bstrBase64Cert)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOriData, (void*)&bstrBase64Cert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_MakeICP10(const QString& bstrSignData, const QString& bstrAsn1Indata, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSignData, (void*)&bstrAsn1Indata, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_MakeP10(const QString& bstrDn, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_MakeP10AccPub(const QString& bstrDn, const QString& bstrPub, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&bstrPub, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_OpenEnvelope(const QString& bstrEnvelope)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrEnvelope};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int CACtrlCom::KS_OpenIE(const QString& ieUrl)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&ieUrl};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_ReadFromKey(int iType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_ReceiveCert(const QString& bstrID, const QString& bstrServerAdd)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrServerAdd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
    return qax_result;
}

inline int CACtrlCom::KS_RemoveCert()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_SM3HashWithPreProcess(const QString& pcPub, const QString& Indata, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pcPub, (void*)&Indata, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SaveCert(const QString& bstrSignCert, const QString& bstrEncCert, const QString& bstrEncKey)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSignCert, (void*)&bstrEncCert, (void*)&bstrEncKey};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SaveCertChain(const QString& bstrP7CertChain)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP7CertChain};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SaveImage(const QString& bStrCn, const QString& bStrO, const QString& filePath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bStrCn, (void*)&bStrO, (void*)&filePath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SendP10(const QString& bstrID, const QString& bstrP10, const QString& bstrDn, const QString& bstrIP, int port)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrP10, (void*)&bstrDn, (void*)&bstrIP, (void*)&port};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetConfigToKey(const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetImageToKey(const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetParam(const QString& bstrParamName, const QString& bstrParamData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrParamName, (void*)&bstrParamData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetProv(const QString& bstrProv, int lAlg, const QString& bstrPath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrProv, (void*)&lAlg, (void*)&bstrPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetServiceAdd(int bstrID, const QString& bstrAddr)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrAddr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 74, _a);
    return qax_result;
}

inline int CACtrlCom::KS_SetSoftKey(const QString& bstrAppName, const QString& bstrContName, const QString& bstrPin, const QString& bstrAppID, const QString& bstrDevName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrAppName, (void*)&bstrContName, (void*)&bstrPin, (void*)&bstrAppID, (void*)&bstrDevName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 75, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_SignData(const QString& bstrInData, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_SymmDecrypt(const QString& bstrEncData, const QString& bstrKey, int lSymmAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrEncData, (void*)&bstrKey, (void*)&lSymmAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 77, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_SymmEncrypt(const QString& bstrOriData, const QString& bstrKey, int lSymmAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOriData, (void*)&bstrKey, (void*)&lSymmAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 78, _a);
    return qax_result;
}

inline int CACtrlCom::KS_Test()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 79, _a);
    return qax_result;
}

inline int CACtrlCom::KS_UnblockPIN(const QString& bstrAdminPIN, const QString& bstrUserPIN)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrAdminPIN, (void*)&bstrUserPIN};
    qt_metacall(QMetaObject::InvokeMetaMethod, 80, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_UniversalHashData(const QString& bstrInData, const QString& bstrCert, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrCert, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 81, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_UniversalHashFile(const QString& bstrData, const QString& bstrFile, int lAlg, const QString& bstrCert)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrData, (void*)&bstrFile, (void*)&lAlg, (void*)&bstrCert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 82, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_UniversalSignData(const QString& bstrData, const QString& bstrInData, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrData, (void*)&bstrInData, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 83, _a);
    return qax_result;
}

inline void CACtrlCom::KS_UniversalVerifySignData(const QString& bstrData, const QString& bstrInData, const QString& bstrSignData)
{
    void *_a[] = {0, (void*)&bstrData, (void*)&bstrInData, (void*)&bstrSignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 84, _a);
}

inline int CACtrlCom::KS_VerifyCertVaild(const QString& bstrCert)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 85, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifyESignSeal(const QString& bstrESignSealData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrESignSealData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 86, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifyP7SignData(const QString& bstrP7SignData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP7SignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 87, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifyPIN()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 88, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifySeal(const QString& bstrSealId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 89, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifySignData(const QString& bstrInData, const QString& bstrSignData, const QString& bstrCert, int lHashAlg)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrSignData, (void*)&bstrCert, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 90, _a);
    return qax_result;
}

inline int CACtrlCom::KS_VerifySoftPIN(const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 91, _a);
    return qax_result;
}

inline int CACtrlCom::KS_WriteToKey(int iType, const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iType, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 92, _a);
    return qax_result;
}

inline QString CACtrlCom::KS_ZWFWGetASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 93, _a);
    return qax_result;
}

inline int CACtrlCom::SetCert(const QString& strCertBase64)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strCertBase64};
    qt_metacall(QMetaObject::InvokeMetaMethod, 94, _a);
    return qax_result;
}

inline int CACtrlCom::Sign(const QString& bstrInData, QString& bstrSignData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrSignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 95, _a);
    return qax_result;
}

inline int CACtrlCom::TestFunction(int i)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&i};
    qt_metacall(QMetaObject::InvokeMetaMethod, 96, _a);
    return qax_result;
}


inline int ICACtrlCom::GetCN(QString& bstrInfo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInfo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int ICACtrlCom::GetCerBase64(QString& CerBase64)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&CerBase64};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int ICACtrlCom::GetDriverVersion(QString& bstrVersion)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrVersion};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline void ICACtrlCom::GetErrorInfo(int& errCode, QString& bstrErrorMsg)
{
    void *_a[] = {0, (void*)&errCode, (void*)&bstrErrorMsg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline int ICACtrlCom::GetFws(QString& bstrFws)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFws};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int ICACtrlCom::GetSbtgs(QString& bstrPcVid)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPcVid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int ICACtrlCom::GetUserMc(QString& CertUserMc)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&CertUserMc};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int ICACtrlCom::GetYxqz(QString& Yxqz)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Yxqz};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_AZTSignData(const QString& bstrInData)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_ChangeSoftPIN(const QString& bstrOldPin, const QString& bstrNewPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOldPin, (void*)&bstrNewPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_CheckPIN(const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_DeleteEmptyApp()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_DeleteFromKey()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_FormatDev()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GenKeyPair()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GenP10Indata(const QString& bstrDn, const QString& bstrPub, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&bstrPub, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GenRandom(int lLen)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lLen};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetALLDevice()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetAllDeviceSerialNumber()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetCert(int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetCertFromNet(const QString& lID)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 29, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetCertInfo(const QString& bstrCert, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 30, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetCertInfoByOid(const QString& bstrCert, const QString& bstrOid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert, (void*)&bstrOid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetDeviceCSP()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetDeviceSerialNumber()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_GetDeviceStatus()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetDeviceVid()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetESignASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetImage(const QString& bStrShebao, const QString& bStrO)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bStrShebao, (void*)&bStrO};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetImageByParseConfig()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetImageFromKey()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetInfoFromSeal(const QString& bstrSealData, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealData, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_GetLastErrorCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetLastErrorMsg()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetP10Info(const QString& bstrP10, int lAlg, int lType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP10, (void*)&lAlg, (void*)&lType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetParam(const QString& bstrParamName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrParamName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetSeal(const QString& bstrSealId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetSealImage(int lType, const QString& bStrCn)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lType, (void*)&bStrCn};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetSealList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetSignValueFromNet(const QString& lID, int time)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lID, (void*)&time};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetVersion()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetXJLVersion()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_GetZDYFYUsedKeyFactory()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_HashData(const QString& bstrInData, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_HashFile(const QString& bstrFile, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_ImportP12Cert(int lCertType, const QString& bstrBase64P12Cert, const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lCertType, (void*)&bstrBase64P12Cert, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_IsChangeKey()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_MakeEnvelope(const QString& bstrOriData, const QString& bstrBase64Cert)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOriData, (void*)&bstrBase64Cert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_MakeICP10(const QString& bstrSignData, const QString& bstrAsn1Indata, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSignData, (void*)&bstrAsn1Indata, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_MakeP10(const QString& bstrDn, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_MakeP10AccPub(const QString& bstrDn, const QString& bstrPub, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrDn, (void*)&bstrPub, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_OpenEnvelope(const QString& bstrEnvelope)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrEnvelope};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_OpenIE(const QString& ieUrl)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&ieUrl};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_ReadFromKey(int iType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_ReceiveCert(const QString& bstrID, const QString& bstrServerAdd)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrServerAdd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_RemoveCert()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_SM3HashWithPreProcess(const QString& pcPub, const QString& Indata, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pcPub, (void*)&Indata, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SaveCert(const QString& bstrSignCert, const QString& bstrEncCert, const QString& bstrEncKey)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSignCert, (void*)&bstrEncCert, (void*)&bstrEncKey};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SaveCertChain(const QString& bstrP7CertChain)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP7CertChain};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SaveImage(const QString& bStrCn, const QString& bStrO, const QString& filePath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bStrCn, (void*)&bStrO, (void*)&filePath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SendP10(const QString& bstrID, const QString& bstrP10, const QString& bstrDn, const QString& bstrIP, int port)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrP10, (void*)&bstrDn, (void*)&bstrIP, (void*)&port};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetConfigToKey(const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetImageToKey(const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetParam(const QString& bstrParamName, const QString& bstrParamData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrParamName, (void*)&bstrParamData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetProv(const QString& bstrProv, int lAlg, const QString& bstrPath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrProv, (void*)&lAlg, (void*)&bstrPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetServiceAdd(int bstrID, const QString& bstrAddr)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrID, (void*)&bstrAddr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 74, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_SetSoftKey(const QString& bstrAppName, const QString& bstrContName, const QString& bstrPin, const QString& bstrAppID, const QString& bstrDevName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrAppName, (void*)&bstrContName, (void*)&bstrPin, (void*)&bstrAppID, (void*)&bstrDevName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 75, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_SignData(const QString& bstrInData, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_SymmDecrypt(const QString& bstrEncData, const QString& bstrKey, int lSymmAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrEncData, (void*)&bstrKey, (void*)&lSymmAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 77, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_SymmEncrypt(const QString& bstrOriData, const QString& bstrKey, int lSymmAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrOriData, (void*)&bstrKey, (void*)&lSymmAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 78, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_Test()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 79, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_UnblockPIN(const QString& bstrAdminPIN, const QString& bstrUserPIN)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrAdminPIN, (void*)&bstrUserPIN};
    qt_metacall(QMetaObject::InvokeMetaMethod, 80, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_UniversalHashData(const QString& bstrInData, const QString& bstrCert, int lAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrCert, (void*)&lAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 81, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_UniversalHashFile(const QString& bstrData, const QString& bstrFile, int lAlg, const QString& bstrCert)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrData, (void*)&bstrFile, (void*)&lAlg, (void*)&bstrCert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 82, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_UniversalSignData(const QString& bstrData, const QString& bstrInData, int lHashAlg)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrData, (void*)&bstrInData, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 83, _a);
    return qax_result;
}

inline void ICACtrlCom::KS_UniversalVerifySignData(const QString& bstrData, const QString& bstrInData, const QString& bstrSignData)
{
    void *_a[] = {0, (void*)&bstrData, (void*)&bstrInData, (void*)&bstrSignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 84, _a);
}

inline int ICACtrlCom::KS_VerifyCertVaild(const QString& bstrCert)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrCert};
    qt_metacall(QMetaObject::InvokeMetaMethod, 85, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifyESignSeal(const QString& bstrESignSealData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrESignSealData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 86, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifyP7SignData(const QString& bstrP7SignData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrP7SignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 87, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifyPIN()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 88, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifySeal(const QString& bstrSealId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrSealId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 89, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifySignData(const QString& bstrInData, const QString& bstrSignData, const QString& bstrCert, int lHashAlg)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrSignData, (void*)&bstrCert, (void*)&lHashAlg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 90, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_VerifySoftPIN(const QString& bstrPin)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrPin};
    qt_metacall(QMetaObject::InvokeMetaMethod, 91, _a);
    return qax_result;
}

inline int ICACtrlCom::KS_WriteToKey(int iType, const QString& bstrFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iType, (void*)&bstrFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 92, _a);
    return qax_result;
}

inline QString ICACtrlCom::KS_ZWFWGetASN1ByParseJSON(const QString& bstrJsonData, int lFlag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrJsonData, (void*)&lFlag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 93, _a);
    return qax_result;
}

inline int ICACtrlCom::SetCert(const QString& strCertBase64)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strCertBase64};
    qt_metacall(QMetaObject::InvokeMetaMethod, 94, _a);
    return qax_result;
}

inline int ICACtrlCom::Sign(const QString& bstrInData, QString& bstrSignData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&bstrInData, (void*)&bstrSignData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 95, _a);
    return qax_result;
}

inline int ICACtrlCom::TestFunction(int i)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&i};
    qt_metacall(QMetaObject::InvokeMetaMethod, 96, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<SecCtrlLib::CACtrlCom, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<SecCtrlLib::CACtrlCom*>(t)->SecCtrlLib::CACtrlCom::~CACtrlCom();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) SecCtrlLib::CACtrlCom;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const SecCtrlLib::CACtrlCom*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<SecCtrlLib::CACtrlCom*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<SecCtrlLib::ICACtrlCom, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<SecCtrlLib::ICACtrlCom*>(t)->SecCtrlLib::ICACtrlCom::~ICACtrlCom();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) SecCtrlLib::ICACtrlCom;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const SecCtrlLib::ICACtrlCom*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<SecCtrlLib::ICACtrlCom*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

